services:
  - type: web
    name: private-ai-agent
    runtime: docker
    plan: free
    branch: main
    autoDeploy: false
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: AGENT_HOST
        value: 0.0.0.0
      - key: AGENT_USERNAME
        sync: false
      - key: AGENT_PASSWORD
        sync: false
      - key: AGENT_SANDBOX_MODE
        value: bubblewrap
      - key: GRADIO_ANALYTICS_ENABLED
        value: 'False'
